services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    environment:
      - GENAI_API_KEY=${GENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    networks:
      - app-network
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
